#fabric
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-fabric-pv
  labels:
    type: nfs
    pv: default-fabric-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/sdb1/appdata/default-fabric
    server: 10.10.38.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-fabric-pvc
  namespace: default
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      pv: default-fabric-pv
