apiVersion: apps/v1
kind: Deployment
metadata:
   namespace: default
   name: cli-org1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli-org1
  template:
    metadata:
      labels:
       app: cli-org1
    spec:
      containers:
        - name: cli-org1
          image:  hyperledger/fabric-tools:1.4.3
          env:
          - name: CORE_VM_ENDPOINT
            value: "unix:///host/var/run/docker.sock"
          - name: GOPATH
            value: "/opt/gopath"
          - name: CORE_LOGGING_LEVEL
            value: "DEBUG"
          - name: CORE_PEER_ID
            value: "cli"
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt"
          - name: CORE_PEER_TLS_KEY_FILE
            value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key"
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
          - name: CORE_PEER_MSPCONFIGPATH
            value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp"
          - name: CORE_PEER_ADDRESS
            value: "peer0.org1.example.com:7051"
          - name: CORE_PEER_LOCALMSPID
            value: "Org1MSP"
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
           - mountPath: /host/var/run/
             name: current-dir
             subPath: data/org1/client/run/
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go/
             name: current-dir
             subPath: chaincode/go/
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
             name: current-dir
             subPath: crypto-config
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
             name: current-dir
             subPath: channel-artifacts
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
             name: current-dir
             subPath: data/org1/client/scripts/
      volumes:
        - name: current-dir
          persistentVolumeClaim:
            claimName: default-fabric-pvc
